/**
 * @NApiVersion 2.1
 * @NScriptType UserEventScript
 */
define(["../Library/lib_series_number.js"], (lib) => {
  const beforeSubmit = (scriptContext) => {
    const newRec = scriptContext.newRecord;

    if (scriptContext.type === scriptContext.UserEventType.CREATE) {
      lib.autoGeneratedSeries({
        newRec: newRec,
      });
    }
  };

  return { beforeSubmit };
});
